# Generated by Django 6.0.1 on 2026-09-04 13:15

import apps.metrics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnonymousUsageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anonymous_id",
                    models.CharField(
                        db_index=True,
                        help_text="Client-generated random ID stored in localStorage. Not linked to accounts.",
                        max_length=64,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page view"),
                            ("heartbeat", "Heartbeat"),
                            ("page_leave", "Page leave"),
                            ("code_run", "Code run"),
                            ("code_reset", "Code reset"),
                            ("evaluate", "Evaluate"),
                            ("feature_select", "Feature select"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("path", models.CharField(blank=True, db_index=True, max_length=255)),
                ("exercise_slug", models.SlugField(blank=True, max_length=200)),
                (
                    "properties",
                    models.JSONField(
                        blank=True, default=apps.metrics.models._default_json_dict
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="metrics_ano_event_t_58aab8_idx",
                    ),
                    models.Index(
                        fields=["exercise_slug", "event_type"],
                        name="metrics_ano_exercis_138d9f_idx",
                    ),
                ],
            },
        ),
    ]
