# Generated by Django 5.x on sitepages feedback storage

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("sitepages", "0001_initial"),
	]

	operations = [
		migrations.CreateModel(
			name="FeedbackSubmission",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("message", models.TextField()),
				("previous_page", models.CharField(blank=True, default="", max_length=500)),
				("want_reply", models.BooleanField(default=False)),
				("reply_email", models.EmailField(blank=True, default="", max_length=254)),
				("user_agent", models.CharField(blank=True, default="", max_length=300)),
				(
					"email_sent",
					models.BooleanField(
						default=False,
						help_text="Whether an email copy was sent successfully when this was submitted.",
					),
				),
				("created_at", models.DateTimeField(auto_now_add=True)),
			],
			options={
				"verbose_name": "feedback submission",
				"verbose_name_plural": "feedback submissions",
				"ordering": ["-created_at"],
			},
		),
	]
