# Generated by Django 6.0.1 on 2026-07-31 09:57

import apps.exercises.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("intro_markdown", models.TextField(blank=True)),
                ("starter_code", models.TextField(blank=True)),
                (
                    "allowed_imports",
                    models.JSONField(
                        blank=True, default=apps.exercises.models._default_json_list
                    ),
                ),
                (
                    "data_definition",
                    models.JSONField(
                        blank=True, default=apps.exercises.models._default_json_dict
                    ),
                ),
                (
                    "evaluation_rules",
                    models.JSONField(
                        blank=True, default=apps.exercises.models._default_json_dict
                    ),
                ),
                ("graphic_markup", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercises",
                        to="courses.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercises",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visitor_key", models.CharField(db_index=True, max_length=64)),
                (
                    "notebook_state",
                    models.JSONField(
                        blank=True, default=apps.exercises.models._default_json_list
                    ),
                ),
                (
                    "data_state",
                    models.JSONField(
                        blank=True, default=apps.exercises.models._default_json_dict
                    ),
                ),
                (
                    "result_state",
                    models.JSONField(
                        blank=True, default=apps.exercises.models._default_json_dict
                    ),
                ),
                (
                    "progress_state",
                    models.JSONField(
                        blank=True, default=apps.exercises.models._default_json_dict
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exercises.exercise",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exercise", "visitor_key"),
                        name="exercise_attempt_unique_visitor",
                    )
                ],
            },
        ),
    ]
