# Generated by Django 6.0.1 on 2026-09-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0005_update_pandas_introduction_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="soft_skill_prompt",
            field=models.TextField(
                blank=True,
                help_text="Reflective soft-skill question shown at the end of the exercise.",
            ),
        ),
        migrations.AddField(
            model_name="exerciseattempt",
            name="soft_skill_response",
            field=models.TextField(blank=True),
        ),
    ]
