# Generated by Django 6.0.1 on 2026-09-09 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0009_data_cleaning_missing_value_mechanics"),
    ]

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("summary", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("published", models.BooleanField(default=False)),
                (
                    "is_placeholder",
                    models.BooleanField(
                        default=False,
                        help_text="Placeholder tracks appear in the catalog but have no exercises yet.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exercises",
                to="exercises.track",
            ),
        ),
    ]
