# Generated by Django 6.0.1 on 2026-09-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0011_seed_tracks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="course",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="lesson",
        ),
    ]
