# Generated by Django 6.0.1 on 2026-09-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0013_update_pandas_introduction_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="is_placeholder",
            field=models.BooleanField(
                default=False,
                help_text="Placeholder exercises appear in the track catalog but are not playable yet.",
            ),
        ),
    ]
