# Generated by Django 6.0.1 on 2026-09-28 07:36

import apps.exercises.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0023_activate_machine_learning_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="exerciseattempt",
            name="attempt_history",
            field=models.JSONField(
                blank=True,
                default=apps.exercises.models._default_json_list,
                help_text="Prior tries for this visitor (try number, timestamp, seed, saved state).",
            ),
        ),
    ]
