"""Badge catalog definitions used by the seed migration and award service."""

BADGE_DEFINITIONS = [
    {
        "slug": "exercise-complete",
        "name": "Exercise Complete",
        "description": "Earned every time you successfully complete an exercise.",
        "category": "exercises",
        "icon": "💪",
        "threshold": 1,
        "sort_order": 5,
        "is_repeatable": True,
    },
    {
        "slug": "first-exercise",
        "name": "First Steps",
        "description": "Complete your first exercise.",
        "category": "exercises",
        "icon": "🌱",
        "threshold": 1,
        "sort_order": 10,
        "is_repeatable": False,
    },
    {
        "slug": "exercise-trio",
        "name": "Getting Rolling",
        "description": "Complete 3 different exercises.",
        "category": "exercises",
        "icon": "🚀",
        "threshold": 3,
        "sort_order": 20,
        "is_repeatable": False,
    },
    {
        "slug": "exercise-collector",
        "name": "Exercise Collector",
        "description": "Complete 5 different exercises.",
        "category": "exercises",
        "icon": "📚",
        "threshold": 5,
        "sort_order": 30,
        "is_repeatable": False,
    },
    {
        "slug": "first-try",
        "name": "First Try",
        "description": "Pass an exercise on the first attempt in a session.",
        "category": "streaks",
        "icon": "🎯",
        "threshold": 1,
        "sort_order": 40,
        "is_repeatable": False,
    },
    {
        "slug": "flawless-five",
        "name": "Flawless Five",
        "description": "Complete 5 exercises in a row without errors.",
        "category": "streaks",
        "icon": "🔥",
        "threshold": 5,
        "sort_order": 50,
        "is_repeatable": False,
    },
    {
        "slug": "daily-ten",
        "name": "Daily Dozen-ish",
        "description": "Complete 10 exercises in a single day.",
        "category": "streaks",
        "icon": "☀️",
        "threshold": 10,
        "sort_order": 60,
        "is_repeatable": False,
    },
    {
        "slug": "ten-hours",
        "name": "Ten Hour Club",
        "description": "Spend 10 hours training on the platform.",
        "category": "streaks",
        "icon": "⏱️",
        "threshold": 36000,
        "sort_order": 65,
        "is_repeatable": False,
    },
    {
        "slug": "forum-newcomer",
        "name": "Forum Newcomer",
        "description": "Make your first forum post.",
        "category": "forum",
        "icon": "💬",
        "threshold": 1,
        "sort_order": 70,
        "is_repeatable": False,
    },
    {
        "slug": "forum-regular",
        "name": "Forum Regular",
        "description": "Share 5 posts in the forum.",
        "category": "forum",
        "icon": "🗣️",
        "threshold": 5,
        "sort_order": 80,
        "is_repeatable": False,
    },
    {
        "slug": "well-received",
        "name": "Well-Received",
        "description": "Receive 5 upvotes on a single forum post.",
        "category": "forum",
        "icon": "⭐",
        "threshold": 5,
        "sort_order": 90,
        "is_repeatable": False,
    },
    {
        "slug": "first-plot",
        "name": "First Plot",
        "description": "Earn the plotting bonus once.",
        "category": "exercises",
        "icon": "📊",
        "threshold": 1,
        "sort_order": 100,
        "is_repeatable": False,
    },
    {
        "slug": "plot-pack",
        "name": "Plot Pack",
        "description": "Earn the plotting bonus on 5 runs.",
        "category": "exercises",
        "icon": "📈",
        "threshold": 5,
        "sort_order": 110,
        "is_repeatable": False,
    },
    {
        "slug": "plot-gallery",
        "name": "Plot Gallery",
        "description": "Earn the plotting bonus on 10 runs.",
        "category": "exercises",
        "icon": "🖼️",
        "threshold": 10,
        "sort_order": 120,
        "is_repeatable": False,
    },
    {
        "slug": "style-spark",
        "name": "Style Spark",
        "description": "Apply 1 custom plot style change (color, marker, or font) for bonus credit.",
        "category": "exercises",
        "icon": "✨",
        "threshold": 1,
        "sort_order": 130,
        "is_repeatable": False,
    },
    {
        "slug": "style-studio",
        "name": "Style Studio",
        "description": "Accumulate 5 plot style customizations across bonus plots.",
        "category": "exercises",
        "icon": "🎨",
        "threshold": 5,
        "sort_order": 140,
        "is_repeatable": False,
    },
    {
        "slug": "style-virtuoso",
        "name": "Style Virtuoso",
        "description": "Accumulate 10 plot style customizations across bonus plots.",
        "category": "exercises",
        "icon": "🖌️",
        "threshold": 10,
        "sort_order": 150,
        "is_repeatable": False,
    },
]
