# Generated by Django 6.0.1 on 2026-09-09 09:08

import apps.badges.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exercises", "0009_data_cleaning_missing_value_mechanics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("exercises", "Exercises"),
                            ("streaks", "Streaks & Speed"),
                            ("forum", "Forum"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🏅",
                        help_text="Emoji shown on the badge card.",
                        max_length=16,
                    ),
                ),
                (
                    "threshold",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Numeric threshold used by award rules (e.g. completions required).",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BadgeActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("run_success", "Run succeeded"),
                            ("run_error", "Run failed"),
                            ("exercise_passed", "Exercise passed"),
                            ("forum_post", "Forum post"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=apps.badges.models._default_json_dict
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="badge_activities",
                        to="exercises.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Badge activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserBadgeStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consecutive_error_free_completions",
                    models.PositiveIntegerField(default=0),
                ),
                ("exercises_completed_count", models.PositiveIntegerField(default=0)),
                ("forum_posts_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=apps.badges.models._default_json_dict
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="badges.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "badge"),
                        name="badges_userbadge_unique_user_badge",
                    )
                ],
            },
        ),
    ]
