# Generated by Django 6.0.1 on 2026-09-15 10:50

from django.db import migrations, models

from apps.badges.catalog import BADGE_DEFINITIONS


PLOT_BADGE_SLUGS = {
    "first-plot",
    "plot-pack",
    "plot-gallery",
    "style-spark",
    "style-studio",
    "style-virtuoso",
}


def seed_plot_badges(apps, schema_editor):
    Badge = apps.get_model("badges", "Badge")
    for definition in BADGE_DEFINITIONS:
        if definition["slug"] not in PLOT_BADGE_SLUGS:
            continue
        Badge.objects.update_or_create(
            slug=definition["slug"],
            defaults={
                "name": definition["name"],
                "description": definition["description"],
                "category": definition["category"],
                "icon": definition["icon"],
                "threshold": definition["threshold"],
                "sort_order": definition["sort_order"],
                "is_active": True,
            },
        )


def unseed_plot_badges(apps, schema_editor):
    Badge = apps.get_model("badges", "Badge")
    Badge.objects.filter(slug__in=PLOT_BADGE_SLUGS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0002_seed_badges"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbadgestats",
            name="plot_modifications_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userbadgestats",
            name="plots_created_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="badgeactivity",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("run_success", "Run succeeded"),
                    ("run_error", "Run failed"),
                    ("exercise_passed", "Exercise passed"),
                    ("forum_post", "Forum post"),
                    ("plot_bonus", "Plotting bonus earned"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.RunPython(seed_plot_badges, unseed_plot_badges),
    ]
