# Generated by Django 6.0.1 on 2026-09-09 08:35

import apps.challenges.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iso_year", models.PositiveIntegerField()),
                ("iso_week", models.PositiveIntegerField()),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
            ],
            options={
                "verbose_name": "Challenge Week",
                "verbose_name_plural": "Challenge Weeks",
                "ordering": ["-iso_year", "-iso_week"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("iso_year", "iso_week"),
                        name="challenges_week_unique_iso",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("data_viz", "Weekly Data Viz"),
                            ("resource", "Resource of the Week"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contests",
                        to="challenges.challengeweek",
                    ),
                ),
            ],
            options={
                "ordering": ["kind"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.challenges.models.challenge_image_upload_to,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="challenges.contest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionUpvote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upvotes",
                        to="challenges.submission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_upvotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="contest",
            constraint=models.UniqueConstraint(
                fields=("week", "kind"), name="challenges_contest_unique_week_kind"
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionupvote",
            constraint=models.UniqueConstraint(
                fields=("submission", "user"), name="challenges_upvote_unique_user"
            ),
        ),
    ]
