# Generated by Django 6.0.1 on 2026-09-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("data_viz", "Weekly Data Viz"),
                    ("resource", "Resource of the Week"),
                    ("misleading_headline", "Misleading Headline"),
                ],
                max_length=32,
            ),
        ),
    ]
