# Generated by Django 6.0.1 on 2026-09-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_soft_skill_and_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="section",
            field=models.CharField(
                choices=[
                    ("exercise", "Exercise Discussions"),
                    ("resources", "Useful Resources"),
                    ("job_market", "Job Market Readiness"),
                    ("achievements", "Celebrate Achievements"),
                    ("general", "Other Discussions"),
                ],
                db_index=True,
                default="general",
                max_length=32,
            ),
        ),
    ]
