# Generated by Django 6.0.1 on 2026-08-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(
                blank=True,
                help_text="Downloadable token for identifying returning forum users.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="forum token",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Optional. Enter your first name.",
                max_length=150,
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Optional. Enter your last name.",
                max_length=150,
                verbose_name="last name",
            ),
        ),
    ]
