# Generated by Django 6.0.1 on 2026-08-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_customuser_token_alter_customuser_first_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_verified",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={"unique": "A user with that email already exists."},
                help_text="Required for staff/admin accounts only. Not collected for regular users.",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="token",
            field=models.CharField(
                blank=True,
                help_text="Downloadable passkey token for identifying returning forum users. No email or password required.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="passkey token",
            ),
        ),
    ]
