# Generated by Django 6.0.1 on 2026-08-31 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0003_remove_customuser_is_verified_alter_customuser_email_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        help_text="A public nickname that must be unique across the platform.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional profile photo.",
                        null=True,
                        upload_to="profile_photos/",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="A short sentence about who you are.",
                        max_length=180,
                    ),
                ),
                (
                    "motivation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Tell others why you are interested in data analysis.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user this profile belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
                "ordering": ["nickname"],
            },
        ),
    ]
