# Generated by Django 6.0.1 on 2026-09-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_connection_notifications_and_blocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_forum_moderator",
            field=models.BooleanField(
                default=False,
                help_text="Designates forum moderators who can remove posts and notify authors about Terms of Service violations. At most five users.",
                verbose_name="forum moderator",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("connection_request", "Connection request"),
                    ("connection_accepted", "Connection accepted"),
                    ("contact_shared", "Contact shared"),
                    ("forum_violation", "Forum terms violation"),
                ],
                max_length=40,
            ),
        ),
    ]
