# Generated by Django 6.0.1 on 2026-09-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_userprofile_preferred_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="exercise_progress",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-exercise personal data state and prior attempt history used to repeat previous attempts.",
            ),
        ),
    ]
