# Generated by Django 6.0.1 on 2026-10-07 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_forum_suspension"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountDeletionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("token_hint", models.CharField(blank=True, default="", max_length=16)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("not_using", "I'm not using the site anymore"),
                            (
                                "too_hard",
                                "Content is too difficult or not the right level",
                            ),
                            ("privacy", "Privacy concerns"),
                            ("other_platform", "I found another platform"),
                            ("technical", "Technical issues"),
                            ("community", "Community or forum concerns"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional details about why the user is leaving.",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional feedback or complaints for the team.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("scheduled_delete_at", models.DateTimeField(db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="How deletion finished: auto, admin, or manual.",
                        max_length=32,
                    ),
                ),
                ("email_sent", models.BooleanField(default=False)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "account deletion request",
                "verbose_name_plural": "account deletion requests",
                "ordering": ["-requested_at"],
            },
        ),
    ]
