"""
Django settings for project_core project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
import sys

from dotenv import load_dotenv

# Sandbox workers must not reload host secrets from .env.
IS_EXERCISE_SANDBOX_WORKER = os.getenv("EXERCISE_SANDBOX_WORKER") == "1"
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
if not IS_EXERCISE_SANDBOX_WORKER:
    # Explicit path so PythonAnywhere loads .env even when CWD differs.
    load_dotenv(BASE_DIR / ".env")
sys.path.insert(0, str(BASE_DIR))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

_WEAK_SECRET_KEYS = {
    "",
    "fallback-secret-key",
    "guest",
    "changeme",
    "secret",
    "django-insecure",
}


def _resolve_secret_key() -> str:
    if IS_EXERCISE_SANDBOX_WORKER:
        # Worker never signs cookies/tokens; keep a non-secret placeholder.
        return "exercise-sandbox-worker-key-not-for-crypto"
    key = (os.getenv("DJANGO_SECRET_KEY") or "").strip().strip("'").strip('"')
    server = os.getenv("SERVER", "development")
    if server != "development":
        if not key or key.lower() in _WEAK_SECRET_KEYS or len(key) < 32:
            raise RuntimeError(
                "DJANGO_SECRET_KEY must be set to a strong value (≥32 chars) when SERVER is not development."
            )
        return key
    if not key or key.lower() in _WEAK_SECRET_KEYS:
        # Development convenience only — never used in production.
        return "dev-only-insecure-secret-key-change-me-32b"
    return key


SECRET_KEY = _resolve_secret_key()
SERVER = os.getenv("SERVER", "development")

# Notebook run endpoint rate limit (per session+IP window).
EXERCISE_RUN_RATE_LIMIT = int(os.getenv("EXERCISE_RUN_RATE_LIMIT", "30"))
EXERCISE_RUN_RATE_WINDOW = int(os.getenv("EXERCISE_RUN_RATE_WINDOW", "60"))
# Must stay comfortably below the gunicorn worker timeout so a slow notebook
# returns an error to the student instead of having its worker killed.
EXERCISE_RUN_TIMEOUT = int(os.getenv("EXERCISE_RUN_TIMEOUT", "45"))
# Number of proxies that append to X-Forwarded-For in front of the app.
# 0 means X-Forwarded-For is untrusted and REMOTE_ADDR is used instead.
TRUSTED_PROXY_COUNT = int(os.getenv("TRUSTED_PROXY_COUNT", "0"))
EXERCISE_ENABLE_RESOURCE_LIMITS = os.getenv("EXERCISE_ENABLE_RESOURCE_LIMITS", "1") != "0"
EXERCISE_ENABLE_SECOND_SEED = os.getenv("EXERCISE_ENABLE_SECOND_SEED", "1") != "0"


def _env_flag(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None or not str(raw).strip():
        return default
    return str(raw).strip().lower() in {"1", "true", "yes", "on"}


def _default_inline_sandbox() -> bool:
    """PythonAnywhere web workers often expose uWSGI as sys.executable."""
    home = (os.getenv("HOME") or "").lower()
    host = (os.getenv("HOSTNAME") or "").lower()
    return "pythonanywhere" in home or "pythonanywhere" in host


# Run notebook code in the web process instead of a subprocess.
EXERCISE_INLINE_SANDBOX = _env_flag("EXERCISE_INLINE_SANDBOX", default=_default_inline_sandbox())
if "test" in sys.argv:
    EXERCISE_RUN_RATE_LIMIT = 10_000
    EXERCISE_ENABLE_RESOURCE_LIMITS = False
    EXERCISE_ENABLE_SECOND_SEED = False
# Worker subprocesses inherit explicit flags via env (see run_notebook).
if IS_EXERCISE_SANDBOX_WORKER:
    EXERCISE_ENABLE_RESOURCE_LIMITS = os.getenv("EXERCISE_ENABLE_RESOURCE_LIMITS", "1") != "0"
    EXERCISE_ENABLE_SECOND_SEED = os.getenv("EXERCISE_ENABLE_SECOND_SEED", "1") != "0"

# SECURITY WARNING: don't run with debug turned on in production!
if SERVER == "development":
    DEBUG = True
else:
    DEBUG = False


def _csv_env(name, default):
    return [value.strip() for value in os.getenv(name, default).split(",") if value.strip()]


# Always honor ALLOWED_HOSTS from the environment when set (needed on PythonAnywhere).
_env_hosts = _csv_env("ALLOWED_HOSTS", "")
if _env_hosts:
    ALLOWED_HOSTS = _env_hosts
elif DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]
else:
    ALLOWED_HOSTS = ["localhost"]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    # Local apps
    "apps.authentication",
    "apps.courses",  # migration history only; curriculum replaced by exercises tracks
    "apps.exercises",
    "apps.forum",
    "apps.challenges",
    "apps.badges",
    "apps.metrics",
    "apps.sitepages",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.sitepages.middleware.SiteAccessMiddleware",
]

# Shared classroom gate password. Empty string disables the gate.
# During `manage.py test`, default to disabled so the suite stays usable;
# gate behavior is covered with @override_settings in sitepages tests.
SITE_ACCESS_PASSWORD = os.getenv(
    "SITE_ACCESS_PASSWORD",
    "" if "test" in sys.argv else "redischoolstudent",
)

ROOT_URLCONF = "project_core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates/"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.authentication.context_processors.unread_notification_count",
            ],
        },
    },
]

WSGI_APPLICATION = "project_core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# DB_ENGINE: sqlite (default, good for PythonAnywhere free) | postgresql | mysql
DB_ENGINE = os.getenv("DB_ENGINE", "sqlite" if SERVER != "production" else "postgresql").lower()

if DB_ENGINE == "postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PWD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }
elif DB_ENGINE == "mysql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PWD"),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "3306"),
            "OPTIONS": {"charset": "utf8mb4"},
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
if SERVER == "production":
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        # Compressed (non-manifest) is more reliable for first deploy / PythonAnywhere.
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "authentication.CustomUser"

LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"
LOGIN_URL = "login"

CSRF_TRUSTED_ORIGINS = _csv_env(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:8000",
)

# Security Settings for Production
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = "Lax"
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_REFERRER_POLICY = "same-origin"
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "DENY"
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
else:
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = "Lax"

# Rate limit counters live in the cache, so LocMemCache only works for a single
# process. Point REDIS_URL at a shared instance in production or the limits are
# enforced per worker rather than per site.
REDIS_URL = os.getenv("REDIS_URL", "")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

# Throttles for credential and ingest endpoints (attempts per window).
LOGIN_RATE_LIMIT = int(os.getenv("LOGIN_RATE_LIMIT", "10"))
LOGIN_RATE_WINDOW = int(os.getenv("LOGIN_RATE_WINDOW", "300"))
SITE_GATE_RATE_LIMIT = int(os.getenv("SITE_GATE_RATE_LIMIT", "10"))
SITE_GATE_RATE_WINDOW = int(os.getenv("SITE_GATE_RATE_WINDOW", "300"))
METRICS_RATE_LIMIT = int(os.getenv("METRICS_RATE_LIMIT", "60"))
METRICS_RATE_WINDOW = int(os.getenv("METRICS_RATE_WINDOW", "60"))
PASSKEY_EMAIL_RATE_LIMIT = int(os.getenv("PASSKEY_EMAIL_RATE_LIMIT", "3"))
PASSKEY_EMAIL_RATE_WINDOW = int(os.getenv("PASSKEY_EMAIL_RATE_WINDOW", "900"))

# Real mail is sent as soon as EMAIL_HOST is configured; otherwise messages go
# to the console so local development never needs an SMTP server.
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "1") != "0"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "0") == "1"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))
if "test" in sys.argv:
    EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"
elif EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@localhost")
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "admin@localhost")
FEEDBACK_TO_EMAIL = os.getenv("FEEDBACK_TO_EMAIL", ADMIN_EMAIL)
ADMINS = [("Site Admin", ADMIN_EMAIL)]
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "console": {
#             "class": "logging.StreamHandler",
#         },
#     },
#     "loggers": {
#         "django.db.backends": {
#             "handlers": ["console"],
#             "level": "DEBUG",
#         },
#     },
# }
